name: build

on: push
jobs:
  my-job:
    runs-on: self-hosted
    steps:
      - name: Get arkade
        run: arkade get inlets-pro
      - name: Set license
        run : |
          mkdir $HOME/.inlets/
          echo ${{secrets.INLETS_LICENSE}} > $HOME/.inlets/LICENSE
      - name: Run tunnel
        run: |
          $HOME/.arkade/bin/inlets-pro http client \
            --token=${{secrets.INLETS_TOKEN}} \
            --url=wss://{{$secrets.INLETS_URL}} \
            --upstream=http://127.0.0.1:8080 \
            --license-file $HOME/.inlets/LICENSE \
            --auto-tls=false &
      - name: Run Nginx
        run: |
          docker run --name nginx -d nginx -p 8080:80
      - name: Sleep a while
        run: |
          sleep 120
